alias gs='git status --ahead-behind'
alias gl='git log --oneline --max-count=42'
alias gl1='git log --max-count=1'
alias glg='git log --graph --oneline --branches --max-count=24 @'
alias glga='git log --graph --oneline --branches @'
alias gd='git diff'
alias gds='git diff --stat'
alias gdw='git diff --word-diff-regex=.'
alias gdt='git difftool --dir-diff --no-symlinks'
alias gdtm='git difftool --dir-diff --no-symlinks origin/main'
alias gdts='git difftool --no-prompt'
alias gdtsm='git difftool --no-prompt origin/main'
alias gmt='git mergetool'
alias gf='git fetch'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpsup='git push --set-upstream origin $(git branch --show-current)'
alias gcan!='git commit --all --amend --no-edit'
alias grasq='git rebase --interactive --autosquash origin/main'
alias gcof='git checkout "$(git branch --format=\"%(refname:short)" | fzf)"'
alias ll='ls -lF'
alias la='ls -A'
alias l='ls -CF'

# alias bb='bzl build //...'
# alias bt='bzl test //...'
# alias bbt='bzl build //... && bzl test //...'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
# alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# alias pbcopy='xsel -ib'
# alias pbpaste='xsel -ob'
